name: Build and deploy Python app to Azure Web App - TECHIN510-LAB9

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Check Python version
        run: |
          python --version
          which python
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
      - name: Unzip artifact for deployment
        run: unzip release.zip
      - name: Navigate to app directory
        run: cd my-flask-app
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CDCB5203C3DD4EE78CC575878A0A15CE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7DFE3881A9C54EB29FE36B2E6D53CEFE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_81545BF5F6B24CF59A459DCF5F69B5C6 }}
      - name: Start Flask app
        run: |
          export FLASK_APP=presidents.py
          flask run --host=0.0.0.0 --port=8000
        env:
          FLASK_ENV: production
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "TECHIN510-LAB9"
          slot-name: "Production"
